services:
  - type: web
    name: nvidia-deepseek-proxy
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: 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
        sync: false